/**
 * \file OsTasks.c
 * \brief FreeRTOS demo tasks for TC3xx controllers
 *
 * \copyright Copyright (c) 2020 Infineon Technologies AG. All rights reserved.
 *
 *                               IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include "Ifx_Types.h"
#include "Compilers.h"
#include "IfxStm.h"
#include "FreeRTOS.h"
#include "task.h"
#include "Leds.h"

#include "DS18B20.h"
#include "ASCLIN_Shell_UART.h"

volatile uint32 count_1ms,
				count_5ms,
				count_10ms,
				count_50ms,
				count_100ms,
				count_500ms,
				count_1000ms;

/**
 * FreeRTOS Kernel Tick timer setup
 * FreeRTOS needs kernel Tick through an interrupt occurring at configTICK_RATE_HZ rate.
 * The ISR need to call the function vPortSystemTickHandler.
 */
static void OsTasks_setupTimerInterrupt(Ifx_STM *stm)
{
    IfxStm_setCompareControl(stm,
                             IfxStm_Comparator_0,
                             IfxStm_ComparatorOffset_0,
                             IfxStm_ComparatorSize_32Bits,
                             IfxStm_ComparatorInterrupt_ir0);

    IfxStm_clearCompareFlag(stm,
                            IfxStm_Comparator_0);

    {
        volatile Ifx_SRC_SRCR *src;
        src = IfxStm_getSrcPointer(stm, IfxStm_Comparator_0);
        IfxSrc_init(src, (IfxSrc_Tos)IfxSrc_Tos_cpu0, configKERNEL_INTERRUPT_PRIORITY);
        IfxSrc_enable(src);
    }

    {
        uint32 stmCount= IfxStm_getLower(stm);
        IfxStm_updateCompare(&MODULE_STM0,
                             IfxStm_Comparator_0,
                             stmCount + (configSTM_CLOCK_HZ/configTICK_RATE_HZ )* 100 );
        IfxStm_enableComparatorInterrupt(stm, IfxStm_Comparator_0);
    }
}

/**
 * FreeRTOS Kernel Tick interrupt provider
 * FreeRTOS needs kernel Tick through an interrupt occurring at configTICK_RATE_HZ rate.
 * The ISR need to call the function vPortSystemTickHandler.
 */
IFX_INTERRUPT(OsTasks_TickProvider, 0, configKERNEL_INTERRUPT_PRIORITY)
{
	uint32 stmCount= IfxStm_getCompare(&MODULE_STM0, IfxStm_Comparator_0);
	IfxStm_updateCompare(&MODULE_STM0,
	                             IfxStm_Comparator_0,
	                             stmCount + configSTM_CLOCK_HZ/configTICK_RATE_HZ );
    vPortSystemTickHandler();
}

static __attribute__((__noreturn__)) void OsTasks_periodicTask_1ms(void *arg)
{
	TickType_t xLastWakeTime;
	(void)arg;
	xLastWakeTime = xTaskGetTickCount();

	while (1)
	{
		vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(1));
		count_1ms++;
#if 0
		measureMyTimePeriod(&measurements.timePeriod_1msTask);
		t32_printf("OS 1ms task resumed! Count= %d \n", count_1ms);
#endif
	}
}

static __attribute__((__noreturn__)) void OsTasks_periodicTask_5ms(void *arg)
{
	TickType_t xLastWakeTime;
	(void)arg;
	xLastWakeTime = xTaskGetTickCount();

	while (1)
	{
		vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(5));
		count_5ms++;
#if 0
		measureMyTimePeriod(&measurements.timePeriod_5msTask);
		t32_printf("OS 5ms task resumed! Count= %d \n", count_5ms);
#endif
	}
}

static __attribute__((__noreturn__)) void OsTasks_periodicTask_10ms(void *arg)
{
	TickType_t xLastWakeTime;
	(void)arg;
	xLastWakeTime = xTaskGetTickCount();

	while (1)
	{
		vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(10));
		count_10ms++;
#if 0
		measureMyTimePeriod(&measurements.timePeriod_10msTask);
		t32_printf("OS 10ms task resumed! Count= %d \n", count_10ms);
#endif
	}
}

static __attribute__((__noreturn__)) void OsTasks_periodicTask_50ms(void *arg)
{
	TickType_t xLastWakeTime;
	(void)arg;
	xLastWakeTime = xTaskGetTickCount();

	while (1)
	{
		vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(50));
		count_50ms++;
#if 0
		measureMyTimePeriod(&measurements.timePeriod_50msTask);
		t32_printf("OS 50ms task resumed! Count= %d \n", count_50ms);
#endif
	}
}

static __attribute__((__noreturn__)) void OsTasks_periodicTask_100ms(void *arg)
{
	TickType_t xLastWakeTime;
	(void)arg;
	xLastWakeTime = xTaskGetTickCount();

	while (1)
	{
		vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(100));
		count_100ms++;
#if 0
		measureMyTimePeriod(&measurements.timePeriod_100msTask);
		t32_printf("OS 100ms task resumed! Count= %d \n", count_100ms);
#endif
	}
}

static __attribute__((__noreturn__)) void OsTasks_periodicTask_500ms(void *arg)
{
	TickType_t xLastWakeTime;
	(void)arg;
	xLastWakeTime = xTaskGetTickCount();

	while (1)
	{
		vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(500));
		count_500ms++;
#if 0
		measureMyTimePeriod(&measurements.timePeriod_500msTask);
		t32_printf("OS 500ms task resumed! Count= %d \n", count_500ms);
#endif
	}
}

static __attribute__((__noreturn__)) void OsTasks_periodicTask_1000ms(void *arg)
{
	TickType_t xLastWakeTime;
	(void)arg;
	xLastWakeTime = xTaskGetTickCount();

	while (1)
	{
		vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(1000));
		count_1000ms++;
#if 0
		measureMyTimePeriod(&measurements.timePeriod_1000msTask);
		t32_printf("OS 1000ms task resumed! Count= %d \n", count_1000ms);
#endif
	}
}

static __attribute__((__noreturn__)) void OsTasks_led0_task(void *arg)
{
	(void)arg;

	while (1)
	{
		vTaskDelay(pdMS_TO_TICKS(500));
		LED_Toggle(&LED_0);
	}
}

void vApplicationIdleHook( void )
{
	uint32 cnt=0;
//	uint32 switchCount= 0;
    /* Set the Kernel interrupt and timer interrupt */
#if 0
    t32_printf("Initializing the STM0 Timer!\n");
#endif
    OsTasks_setupTimerInterrupt(&MODULE_STM0);

	while (1)
	{
		if (cnt != count_1000ms)
		{
#if 0
			switch (switchCount)
			{
				case 0:
					t32_printf("OS 1ms task measurements: \n");
					t32_printf("    Count= %d \n", count_1ms);
					t32_printf("    Delta time=     %5.4f ms \n", measurements.timePeriod_1msTask.average.time);
					t32_printf("    Max delta time= %5.4f ms \n", measurements.timePeriod_1msTask.max.time);
					t32_printf("    Min delta time= %5.4f ms \n", measurements.timePeriod_1msTask.min.time);
					break;
				case 1:
					t32_printf("OS 5ms task measurements: \n");
					t32_printf("    Count= %d \n", count_5ms);
					t32_printf("    Delta time=     %5.4f ms \n", measurements.timePeriod_5msTask.average.time);
					t32_printf("    Max delta time= %5.4f ms \n", measurements.timePeriod_5msTask.max.time);
					t32_printf("    Min delta time= %5.4f ms \n", measurements.timePeriod_5msTask.min.time);
					break;
				case 2:
					t32_printf("OS 10ms task measurements: \n");
					t32_printf("    Count= %d \n", count_10ms);
					t32_printf("    Delta time=     %6.4f ms \n", measurements.timePeriod_10msTask.average.time);
					t32_printf("    Max delta time= %6.4f ms \n", measurements.timePeriod_10msTask.max.time);
					t32_printf("    Min delta time= %6.4f ms \n", measurements.timePeriod_10msTask.min.time);
					break;
				case 3:
					t32_printf("OS 50ms task measurements: \n");
					t32_printf("    Count= %d \n", count_50ms);
					t32_printf("    Delta time=     %6.4f ms \n", measurements.timePeriod_50msTask.average.time);
					t32_printf("    Max delta time= %6.4f ms \n", measurements.timePeriod_50msTask.max.time);
					t32_printf("    Min delta time= %6.4f ms \n", measurements.timePeriod_50msTask.min.time);
					break;
				case 4:
					t32_printf("OS 100ms task measurements: \n");
					t32_printf("    Count= %d \n", count_100ms);
					t32_printf("    Delta time=     %7.4f ms \n", measurements.timePeriod_100msTask.average.time);
					t32_printf("    Max delta time= %7.4f ms \n", measurements.timePeriod_100msTask.max.time);
					t32_printf("    Min delta time= %7.4f ms \n", measurements.timePeriod_100msTask.min.time);
					break;
				case 5:
					t32_printf("OS 500ms task measurements: \n");
					t32_printf("    Count= %d \n", count_500ms);
					t32_printf("    Delta time=     %7.4f ms \n", measurements.timePeriod_500msTask.average.time);
					t32_printf("    Max delta time= %7.4f ms \n", measurements.timePeriod_500msTask.max.time);
					t32_printf("    Min delta time= %7.4f ms \n", measurements.timePeriod_500msTask.min.time);
					break;
				case 6:
					t32_printf("OS 1000ms task measurements: \n");
					t32_printf("    Count= %d \n", count_1000ms);
					t32_printf("    Delta time=     %8.4f ms \n", measurements.timePeriod_1000msTask.average.time);
					t32_printf("    Max delta time= %8.4f ms \n", measurements.timePeriod_1000msTask.max.time);
					t32_printf("    Min delta time= %8.4f ms \n", measurements.timePeriod_1000msTask.min.time);
					break;
				default:
					break;
			}
			if(switchCount++ >= 6) switchCount= 0;
#endif
			cnt= count_1000ms;
		}
	}
}

static __attribute__((__noreturn__)) void OsTasks_shell_task(void *arg)
{
   initShellInterface();
   while(1){
       vTaskDelay(pdMS_TO_TICKS(10));
       runShellInterface();
   }
}

static __attribute__((__noreturn__)) void OsTasks_test(void *arg)
{
   while(1){
       vTaskDelay(pdMS_TO_TICKS(1000));
       broadcastConvert();
       float32 x = getTemperature();
       char temp[20];

       sprintf(temp, "temp: %.2f\n\r", x);
       printToConsole(temp);

   }
}


void OS_Tasks_init(void)
{
    LED_Init(&LED_0);
    LED_Init(&LED_1);
//    initMyTimePeriod();

    /* Create tasks. */
    xTaskCreate(OsTasks_shell_task, "shelling", configMINIMAL_STACK_SIZE, NULL, 8, NULL);
    xTaskCreate(OsTasks_test, "test", configMINIMAL_STACK_SIZE, NULL, 8, NULL);
    xTaskCreate(OsTasks_led0_task, "LED0 task", configMINIMAL_STACK_SIZE, NULL, 10, NULL);
    xTaskCreate(OsTasks_periodicTask_1ms, "1ms task", configMINIMAL_STACK_SIZE, NULL, 9, NULL);
    xTaskCreate(OsTasks_periodicTask_5ms, "5ms task", configMINIMAL_STACK_SIZE, NULL, 8, NULL);
    xTaskCreate(OsTasks_periodicTask_10ms, "10ms task", configMINIMAL_STACK_SIZE, NULL, 7, NULL);
    xTaskCreate(OsTasks_periodicTask_50ms, "50ms task", configMINIMAL_STACK_SIZE, NULL, 6, NULL);
    xTaskCreate(OsTasks_periodicTask_100ms, "100ms task", configMINIMAL_STACK_SIZE, NULL, 5, NULL);
    xTaskCreate(OsTasks_periodicTask_500ms, "500ms task", configMINIMAL_STACK_SIZE, NULL, 4, NULL);
    xTaskCreate(OsTasks_periodicTask_1000ms, "1000ms task", configMINIMAL_STACK_SIZE, NULL, 3, NULL);


#if 0
    t32_printf("Hi there! \nNow initializing the OS!\n");
#endif

    /* Start the tasks running. */
    vTaskStartScheduler();
}
